### ISSUE TITLE
Support `python-version-file` argument for `setup-python`

### ISSUE THREAD

**Issue by evansd** [opensafely-core/setup-action#14]
This would allow us to avoid repeatedly hardcoding the Python version throughout the workflow files and give us a single place to update:
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input

I imagine using it like:
```yaml
steps:
  - uses: "opensafely-core/setup-action@v1"
    with:
      python-version-file: ".python-version"
      cache-dependency-path: "requirements.*.txt"
      install-just: true
```
